-- Seeds a starter list of real Nigerian tertiary institutions so the
-- registration school picker has meaningful data instead of a single
-- manually-entered row. Skips any name already present (idempotent),
-- so this is safe to re-run and won't duplicate "University of Lagos".

insert into public.schools (name)
select name from unnest(array[
  -- Federal universities
  'University of Lagos',
  'University of Ibadan',
  'University of Nigeria, Nsukka',
  'Obafemi Awolowo University',
  'Ahmadu Bello University',
  'University of Benin',
  'University of Ilorin',
  'Federal University of Technology, Akure',
  'Federal University of Technology, Owerri',
  'University of Port Harcourt',
  'University of Jos',
  'Bayero University Kano',
  'University of Calabar',
  'University of Maiduguri',
  'Federal University of Agriculture, Abeokuta',
  'Nnamdi Azikiwe University',
  'University of Uyo',
  'Usmanu Danfodiyo University, Sokoto',
  'Federal University, Oye-Ekiti',
  'Modibbo Adama University, Yola',
  'Michael Okpara University of Agriculture, Umudike',
  'Federal University Dutsin-Ma',
  'Nigerian Defence Academy',
  'National Open University of Nigeria',
  -- State universities
  'Lagos State University',
  'Ekiti State University',
  'Rivers State University',
  'Imo State University',
  'Delta State University',
  'Kaduna State University',
  'Kano University of Science and Technology, Wudil',
  'Enugu State University of Science and Technology',
  'Abia State University',
  'Benue State University',
  'Ambrose Alli University',
  'Ladoke Akintola University of Technology',
  'Olabisi Onabanjo University',
  'Kwara State University',
  'Osun State University',
  'Adekunle Ajasin University',
  'Niger Delta University',
  'Plateau State University',
  'Taraba State University',
  'Ondo State University of Science and Technology',
  -- Private universities
  'Covenant University',
  'Babcock University',
  'Bowen University',
  'Afe Babalola University',
  'Pan-Atlantic University',
  'Redeemer''s University',
  'Landmark University',
  'Bells University of Technology',
  'American University of Nigeria',
  'Nile University of Nigeria',
  'Lead City University',
  'Caleb University',
  'Crawford University',
  'Elizade University',
  'Veritas University',
  -- Polytechnics
  'Yaba College of Technology',
  'Federal Polytechnic, Nekede',
  'The Polytechnic, Ibadan',
  'Kaduna Polytechnic',
  'Auchi Polytechnic',
  'Federal Polytechnic, Ilaro',
  'Lagos State Polytechnic',
  'Kwara State Polytechnic',
  'Rufus Giwa Polytechnic',
  -- Colleges of education
  'Federal College of Education, Zaria',
  'Adeyemi Federal University of Education',
  'Alvan Ikoku Federal College of Education'
]) as name
where name not in (select schools.name from public.schools);
